import React from 'react';
import { Report } from '@/types/report';
import { sections } from '@/constants/reportSections';
import ReportSection from './ReportSection';

interface ReportContentProps {
  report: Report;
  isConnected: boolean;
  address: string | undefined;
  hasPaid: boolean;
}

export default function ReportContent({ report, isConnected, address, hasPaid }: ReportContentProps) {
  // 只有已登录且是创建者或已支付的用户才能看到完整内容
  const canViewFullContent = isConnected && address && (report.user_address === address || hasPaid);

  return (
    <div>
      {/* 项目名称 */}
      <div className="sticky top-16 bg-gradient-to-r from-[#0F172A] to-[#1E293B] z-10 pb-4 mb-8 backdrop-blur-md">
        <h1 className="text-3xl font-bold pt-4 bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
          {report.projectName}
        </h1>
      </div>

      {/* 项目简介 - 始终显示 */}
      <div id="summary" className="glass-effect rounded-xl p-6 mb-8">
        <h2 className="text-xl font-semibold mb-4 bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
          Project Overview
        </h2>
        <div className="space-y-4">
          <p className="text-gray-300 whitespace-pre-line">
            {report.summary}
          </p>
        </div>
      </div>

      {/* 完整内容 */}
      {canViewFullContent && (
        <div className="space-y-12">
          {sections.map(section => (
            section.id !== 'summary' && (
              <ReportSection 
                key={section.id} 
                section={section} 
                report={report} 
              />
            )
          ))}
          
          {/* 免责声明 */}
          <div className="text-center text-sm text-gray-400 italic mt-8 pt-8 border-t border-gray-700">
            This report is generated by AI. Please use the information with discretion.
          </div>
        </div>
      )}
    </div>
  );
} 